import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg = window.TAHWEESHTI_CONFIG || {};
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const state = { mode:'local', client:null, user:null, entries:[], payments:[], editingId:null, paymentEntryId:null, pendingReceipt:null, authMode:'login', installPrompt:null };
const LOCAL_KEY='tahweeshti_local_v2';
const JOD = n => `${Number(n||0).toLocaleString('ar-JO',{minimumFractionDigits:0,maximumFractionDigits:3})} ${cfg.currencyLabel||'د.أ'}`;
const today = () => new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Amman'});
const esc = v => String(v??'').replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid = () => crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const isSupabaseConfigured = () => /^https:\/\/.+\.supabase\.co$/i.test(cfg.supabaseUrl||'') && cfg.supabaseAnonKey && !String(cfg.supabaseAnonKey).startsWith('YOUR_');

function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function loading(on=true){$('#loading').classList.toggle('hidden',!on)}
function openModal(id){const m=$('#'+id);m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(id){const m=$('#'+id);m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));

function localLoad(){const raw=localStorage.getItem(LOCAL_KEY);if(!raw)return {entries:[],payments:[]};try{return JSON.parse(raw)}catch{return {entries:[],payments:[]}}}
function localSave(){localStorage.setItem(LOCAL_KEY,JSON.stringify({entries:state.entries,payments:state.payments,version:2,updatedAt:new Date().toISOString()}))}
function setMode(mode){state.mode=mode;$('#modeBadge').textContent=mode==='supabase'?'متصل':'تجريبي محلي';$('#modeBadge').style.color=mode==='supabase'?'var(--emerald)':'var(--gold)';$('#connectionInfo').textContent=mode==='supabase'?'متصل بـ Supabase — بياناتك تتزامن بين أجهزتك.':'الوضع المحلي — البيانات محفوظة على هذا الجهاز فقط. اربط Supabase للمزامنة.';$('#accountInfo').textContent=mode==='supabase'?(state.user?.email||'حساب Supabase'):'لا يوجد حساب في الوضع المحلي.'}

async function init(){
  setTimeout(()=>$('#splash').classList.add('hide'),850);
  $('#entryDate').value=today();$('#paymentDate').value=today();$('#todayLabel').textContent=new Intl.DateTimeFormat('ar-JO',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Amman'}).format(new Date());
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
  if(isSupabaseConfigured()){
    state.mode='supabase';state.client=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    const {data:{session}}=await state.client.auth.getSession();
    if(session?.user){state.user=session.user;await enterApp()}else showAuth();
    state.client.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session?.user){state.user=session.user;await enterApp()}if(event==='SIGNED_OUT'){state.user=null;showAuth()}});
  }else showAuth(true);
  bind();
}

function showAuth(localAvailable=false){$('#app').classList.add('hidden');$('#authScreen').classList.remove('hidden');$('#demoBtn').classList.toggle('hidden',!localAvailable);$('#authSubtitle').textContent=localAvailable?'Supabase لسه مش مربوط. تقدر تجرب البرنامج محليًا الآن.':'سجّل دخولك حتى تتزامن حركاتك بين كل أجهزتك.'}
async function enterApp(){loading(true);try{if(state.mode==='supabase')await fetchData();else{const d=localLoad();state.entries=d.entries||[];state.payments=d.payments||[]}setMode(state.mode);$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');navigate('dashboard');renderAll()}catch(e){console.error(e);toast('تعذر تحميل البيانات')}finally{loading(false)}}

async function fetchData(){
  const [e,p]=await Promise.all([
    state.client.from('entries').select('*').order('entry_date',{ascending:false}).order('created_at',{ascending:false}),
    state.client.from('payments').select('*').order('payment_date',{ascending:false}).order('created_at',{ascending:false})
  ]);
  if(e.error)throw e.error;if(p.error)throw p.error;
  state.entries=(e.data||[]).map(mapEntry);state.payments=(p.data||[]).map(mapPayment);
}
function mapEntry(x){return {id:x.id,type:x.type,person:x.person||'',amount:Number(x.amount||0),date:x.entry_date,note:x.note||'',receiptPath:x.receipt_path||'',createdAt:x.created_at,updatedAt:x.updated_at}}
function mapPayment(x){return {id:x.id,entryId:x.entry_id,amount:Number(x.amount||0),date:x.payment_date,note:x.note||'',createdAt:x.created_at}}
function entryPaid(id){return state.payments.filter(p=>p.entryId===id).reduce((a,p)=>a+Number(p.amount||0),0)}
function enrich(e){const paid=entryPaid(e.id),debt=['receivable','payable'].includes(e.type),remaining=debt?Math.max(0,Number(e.amount)-paid):0,status=!debt?'na':remaining<=.0001?'paid':paid>0?'partial':'open';return {...e,paid,remaining,status}}
function allEntries(){return state.entries.map(enrich)}
function totals(){let r=0,p=0,i=0,x=0;allEntries().forEach(e=>{if(e.type==='receivable')r+=e.remaining;if(e.type==='payable')p+=e.remaining;if(e.type==='income')i+=e.amount;if(e.type==='expense')x+=e.amount});return {r,p,i,x,net:r-p+i-x}}
const typeInfo=t=>({receivable:['💚','إلي','pos'],payable:['🔴','عليّ','neg'],income:['📈','إيراد','pos'],expense:['📉','مصروف','neg']}[t]||['🧾','حركة','']);

function animateNumber(el,target){const from=Number(el.dataset.value||0),start=performance.now(),dur=500;el.dataset.value=target;const step=now=>{const t=Math.min(1,(now-start)/dur),e=1-Math.pow(1-t,3),v=from+(target-from)*e;el.textContent=JOD(v);if(t<1)requestAnimationFrame(step)};requestAnimationFrame(step)}
function renderAll(){renderStats();renderRecent();renderEntries();renderDebts();setMode(state.mode)}
function renderStats(){const t=totals();animateNumber($('#receivableTotal'),t.r);animateNumber($('#payableTotal'),t.p);animateNumber($('#incomeTotal'),t.i);animateNumber($('#expenseTotal'),t.x);animateNumber($('#netBalance'),t.net);$('#netBalance').classList.toggle('neg',t.net<0);$('#netHint').textContent=state.entries.length?`${state.entries.length} حركة مسجلة — آخر تحديث الآن`:'ابدأ بإضافة أول حركة'}
function renderRecent(){const arr=allEntries().sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date))).slice(0,6),box=$('#recentList');if(!arr.length){box.innerHTML=empty('ما في حركات لسه','أضف أول حركة من زر +');return}box.innerHTML=arr.map((e,i)=>{const [ic,label,cls]=typeInfo(e.type),debt=['receivable','payable'].includes(e.type),amount=debt?e.remaining:e.amount;return `<div class="activity-row" style="--i:${i}"><div class="activity-icon">${ic}</div><div class="activity-main"><b>${esc(e.person||label)}</b><small>${label} · ${esc(e.date)}${e.note?' · '+esc(e.note):''}</small></div><div class="activity-amount ${cls}">${JOD(amount)}</div></div>`}).join('')}
function renderEntries(){const q=$('#searchInput').value.trim().toLowerCase(),tf=$('#typeFilter').value,sf=$('#statusFilter').value;let arr=allEntries().sort((a,b)=>String(b.date).localeCompare(String(a.date)));arr=arr.filter(e=>(!q||`${e.person} ${e.note}`.toLowerCase().includes(q))&&(tf==='all'||e.type===tf)&&(sf==='all'||e.status===sf||(!['receivable','payable'].includes(e.type)&&sf==='all')));const box=$('#entriesList');if(!arr.length){box.innerHTML=empty('ما لقينا حركات مطابقة','غيّر الفلتر أو أضف حركة جديدة');return}box.innerHTML=arr.map((e,i)=>{const [ic,label,cls]=typeInfo(e.type),debt=['receivable','payable'].includes(e.type),shown=debt?e.remaining:e.amount;return `<article class="entry-card" style="--i:${Math.min(i,12)}"><div class="entry-badge">${ic}</div><div class="entry-main"><h4>${esc(e.person||label)}</h4><div class="entry-meta"><span>${label}</span><span>📅 ${esc(e.date)}</span>${e.note?`<span>📝 ${esc(e.note)}</span>`:''}${e.receiptPath?'<span>📸 إيصال</span>':''}</div></div><div class="entry-money"><strong class="${cls}">${JOD(shown)}</strong>${debt?`<small>الأصل ${JOD(e.amount)} · المدفوع ${JOD(e.paid)}</small>`:''}</div><div class="entry-actions">${debt&&e.remaining>0?`<button class="tiny-btn" data-pay="${e.id}" title="دفعة">💳</button>`:''}${e.receiptPath?`<button class="tiny-btn" data-receipt="${e.id}" title="الإيصال">📸</button>`:''}<button class="tiny-btn" data-edit="${e.id}" title="تعديل">✎</button></div></article>`}).join('');bindDynamic()}
function renderDebts(){const debts=allEntries().filter(e=>['receivable','payable'].includes(e.type)&&e.remaining>0).sort((a,b)=>b.remaining-a.remaining),box=$('#debtsList'),prev=$('#debtPreview');if(!debts.length){box.innerHTML=empty('كل الديون مسكرة 🎉','ما عندك مبالغ مفتوحة حاليًا');prev.innerHTML=empty('ما في ديون مفتوحة','لما تضيف دين رح يظهر هون');return}box.innerHTML=debts.map(e=>{const [ic,label,cls]=typeInfo(e.type),pct=Math.max(0,Math.min(100,(e.paid/e.amount)*100));return `<article class="debt-card glass"><div class="debt-card-top"><span>${ic} ${label}</span><small>${esc(e.date)}</small></div><h4>${esc(e.person||'بدون اسم')}</h4><div class="remaining ${cls}">${JOD(e.remaining)}</div><small>من أصل ${JOD(e.amount)} · مدفوع ${JOD(e.paid)}</small><div class="progress" style="margin-top:12px"><span style="width:${pct}%"></span></div><div class="debt-actions"><button class="btn secondary compact" data-pay="${e.id}">💳 تسجيل دفعة</button><button class="btn ghost compact" data-edit="${e.id}">تفاصيل</button></div></article>`}).join('');prev.innerHTML=debts.slice(0,4).map(e=>{const pct=Math.max(0,Math.min(100,(e.paid/e.amount)*100));return `<div class="debt-mini"><div class="debt-mini-head"><div><b>${esc(e.person||'بدون اسم')}</b><br><small>${e.type==='receivable'?'إلي':'عليّ'}</small></div><strong>${JOD(e.remaining)}</strong></div><div class="progress"><span style="width:${pct}%"></span></div></div>`}).join('');bindDynamic()}
function empty(title,sub){return `<div class="empty-state"><span>◌</span><b>${title}</b><br><small>${sub}</small></div>`}

function navigate(name){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+name)?.classList.add('active');$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));const titles={dashboard:'مساء الخير 👋',transactions:'الحركات المالية',debts:'الديون والدفعات',settings:'الإعدادات'};$('#pageTitle').textContent=titles[name]||'تحويشتي';window.scrollTo({top:0,behavior:'smooth'})}
function bindDynamic(){$$('[data-edit]').forEach(b=>b.onclick=()=>editEntry(b.dataset.edit));$$('[data-pay]').forEach(b=>b.onclick=()=>startPayment(b.dataset.pay));$$('[data-receipt]').forEach(b=>b.onclick=()=>viewReceipt(b.dataset.receipt))}

function resetEntry(type='receivable'){state.editingId=null;state.pendingReceipt=null;$('#entryForm').reset();$('#entryType').value=type;$('#entryDate').value=today();$('#entryModalTitle').textContent='إضافة حركة';$('#deleteEntryBtn').classList.add('hidden');$('#receiptLabel').textContent='JPG / PNG / WEBP — حتى 5MB';updatePersonLabel()}
function quickEntry(type){resetEntry(type);openModal('entryModal')}
function editEntry(id){const e=state.entries.find(x=>x.id===id);if(!e)return;state.editingId=id;state.pendingReceipt=null;$('#entryType').value=e.type;$('#entryAmount').value=e.amount;$('#entryPerson').value=e.person||'';$('#entryDate').value=e.date||today();$('#entryNote').value=e.note||'';$('#entryModalTitle').textContent='تعديل الحركة';$('#deleteEntryBtn').classList.remove('hidden');$('#receiptLabel').textContent=e.receiptPath?'✅ يوجد إيصال محفوظ — اختر صورة لاستبداله':'JPG / PNG / WEBP — حتى 5MB';updatePersonLabel();openModal('entryModal')}
function updatePersonLabel(){const t=$('#entryType').value,debt=['receivable','payable'].includes(t);$('#personLabel').textContent=debt?'اسم الشخص':'الجهة / الوصف';$('#entryPerson').placeholder=debt?'مثال: أحمد':'مثال: راتب / سوبرماركت'}

async function uploadReceipt(file,entryId){if(!file)return '';if(file.size>5*1024*1024)throw new Error('حجم الصورة أكبر من 5MB');if(state.mode==='local')return await fileToDataURL(file);const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${state.user.id}/${entryId}/${Date.now()}.${ext}`;const {error}=await state.client.storage.from('receipts').upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;return path}
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function saveEntry(ev){ev.preventDefault();const type=$('#entryType').value,amount=Number($('#entryAmount').value),person=$('#entryPerson').value.trim(),date=$('#entryDate').value,note=$('#entryNote').value.trim();if(!(amount>0))return toast('اكتب مبلغ صحيح');if(!date)return toast('اختر التاريخ');if(['receivable','payable'].includes(type)&&!person)return toast('اكتب اسم الشخص');loading(true);try{const existing=state.editingId?state.entries.find(x=>x.id===state.editingId):null,id=existing?.id||uid();let receiptPath=existing?.receiptPath||'';if(state.pendingReceipt)receiptPath=await uploadReceipt(state.pendingReceipt,id);const now=new Date().toISOString();if(state.mode==='supabase'){const row={id,user_id:state.user.id,type,person,amount,entry_date:date,note,receipt_path:receiptPath||null};const {error}=await state.client.from('entries').upsert(row,{onConflict:'id'});if(error)throw error;await fetchData()}else{const obj={id,type,person,amount,date,note,receiptPath,createdAt:existing?.createdAt||now,updatedAt:now};state.entries=existing?state.entries.map(x=>x.id===id?obj:x):[obj,...state.entries];localSave()}closeModal('entryModal');renderAll();toast(existing?'تم تعديل الحركة ✅':'تم حفظ الحركة ✅')}catch(e){console.error(e);toast(e.message||'تعذر حفظ الحركة')}finally{loading(false)}}
async function deleteEntry(){if(!state.editingId||!confirm('متأكد من حذف الحركة وكل دفعاتها؟'))return;loading(true);try{const e=state.entries.find(x=>x.id===state.editingId);if(state.mode==='supabase'){const {error}=await state.client.from('entries').delete().eq('id',state.editingId);if(error)throw error;if(e?.receiptPath)await state.client.storage.from('receipts').remove([e.receiptPath]).catch(()=>{});await fetchData()}else{state.entries=state.entries.filter(x=>x.id!==state.editingId);state.payments=state.payments.filter(p=>p.entryId!==state.editingId);localSave()}closeModal('entryModal');renderAll();toast('تم حذف الحركة')}catch(e){console.error(e);toast('تعذر الحذف')}finally{loading(false)}}

function startPayment(id){const e=allEntries().find(x=>x.id===id);if(!e)return;state.paymentEntryId=id;$('#paymentAmount').value='';$('#paymentAmount').max=e.remaining;$('#paymentDate').value=today();$('#paymentNote').value='';$('#paymentHint').textContent=`المتبقي على ${e.person||'الحركة'}: ${JOD(e.remaining)}`;openModal('paymentModal')}
async function savePayment(ev){ev.preventDefault();const e=allEntries().find(x=>x.id===state.paymentEntryId),amount=Number($('#paymentAmount').value),date=$('#paymentDate').value,note=$('#paymentNote').value.trim();if(!e)return;if(!(amount>0)||amount>e.remaining+.0001)return toast('قيمة الدفعة غير صحيحة');loading(true);try{if(state.mode==='supabase'){const {error}=await state.client.from('payments').insert({user_id:state.user.id,entry_id:e.id,amount,payment_date:date,note});if(error)throw error;await fetchData()}else{state.payments.unshift({id:uid(),entryId:e.id,amount,date,note,createdAt:new Date().toISOString()});localSave()}closeModal('paymentModal');renderAll();toast('تم تسجيل الدفعة 💳')}catch(err){console.error(err);toast(err.message||'تعذر حفظ الدفعة')}finally{loading(false)}}

async function viewReceipt(entryId){const e=state.entries.find(x=>x.id===entryId);if(!e?.receiptPath)return;openModal('receiptModal');$('#receiptView').innerHTML='جاري تحميل الصورة...';try{let url=e.receiptPath;if(state.mode==='supabase'){const {data,error}=await state.client.storage.from('receipts').createSignedUrl(e.receiptPath,120);if(error)throw error;url=data.signedUrl}$('#receiptView').innerHTML=`<img src="${esc(url)}" alt="إيصال">`}catch(err){console.error(err);$('#receiptView').textContent='تعذر تحميل الصورة'}}

async function authSubmit(ev){ev.preventDefault();if(!state.client)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;$('#authMessage').textContent='';loading(true);try{if(state.authMode==='login'){const {error}=await state.client.auth.signInWithPassword({email,password});if(error)throw error}else{const {data,error}=await state.client.auth.signUp({email,password});if(error)throw error;if(!data.session){$('#authMessage').textContent='تم إنشاء الحساب. افحص بريدك لتأكيده ثم سجل الدخول.';state.authMode='login';updateAuthMode()}}}catch(e){$('#authMessage').textContent=e.message||'تعذر تسجيل الدخول'}finally{loading(false)}}
function updateAuthMode(){const signup=state.authMode==='signup';$('#loginSubmit span').textContent=signup?'إنشاء حساب':'دخول';$('#toggleAuthMode').textContent=signup?'عندي حساب — تسجيل الدخول':'إنشاء حساب';$('#authPassword').autocomplete=signup?'new-password':'current-password'}
async function logout(){if(state.mode==='supabase'&&state.client)await state.client.auth.signOut();else showAuth(true)}

function exportBackup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),entries:state.entries,payments:state.payments},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tahweeshti-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('تم تنزيل النسخة الاحتياطية')}
async function importBackup(file){if(!file)return;let data;try{data=JSON.parse(await file.text())}catch{return toast('ملف النسخة غير صالح')}if(!Array.isArray(data.entries)||!Array.isArray(data.payments))return toast('صيغة النسخة غير صحيحة');if(!confirm('سيتم دمج/تحديث البيانات الموجودة حسب المعرفات. متابعة؟'))return;loading(true);try{if(state.mode==='supabase'){const erows=data.entries.map(e=>({id:e.id||uid(),user_id:state.user.id,type:e.type,person:e.person||'',amount:Number(e.amount||0),entry_date:e.date,note:e.note||'',receipt_path:null}));if(erows.length){const {error}=await state.client.from('entries').upsert(erows,{onConflict:'id'});if(error)throw error}const prows=data.payments.map(p=>({id:p.id||uid(),user_id:state.user.id,entry_id:p.entryId,amount:Number(p.amount||0),payment_date:p.date,note:p.note||''}));if(prows.length){const {error}=await state.client.from('payments').upsert(prows,{onConflict:'id'});if(error)throw error}await fetchData()}else{const byId=new Map(state.entries.map(x=>[x.id,x]));data.entries.forEach(x=>byId.set(x.id,x));state.entries=[...byId.values()];const pby=new Map(state.payments.map(x=>[x.id,x]));data.payments.forEach(x=>pby.set(x.id,x));state.payments=[...pby.values()];localSave()}renderAll();toast('تم استرجاع النسخة ✅')}catch(e){console.error(e);toast(e.message||'تعذر الاسترجاع')}finally{loading(false);$('#importFile').value=''}}

function bind(){
  $$('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
  $$('[data-quick]').forEach(b=>b.addEventListener('click',()=>quickEntry(b.dataset.quick)));
  $('#quickAddTop').onclick=()=>quickEntry('receivable');$('#addFromTransactions').onclick=()=>quickEntry('receivable');$('#mobileAdd').onclick=()=>quickEntry('receivable');$('#fab').onclick=()=>quickEntry('receivable');
  $('#entryForm').addEventListener('submit',saveEntry);$('#entryType').onchange=updatePersonLabel;$('#deleteEntryBtn').onclick=deleteEntry;
  $('#entryReceipt').onchange=e=>{const f=e.target.files[0];if(!f)return;state.pendingReceipt=f;$('#receiptLabel').textContent=`✅ ${f.name} — ${(f.size/1024/1024).toFixed(2)}MB`};
  $('#paymentForm').addEventListener('submit',savePayment);$('#searchInput').oninput=renderEntries;$('#typeFilter').onchange=renderEntries;$('#statusFilter').onchange=renderEntries;
  $('#refreshBtn').onclick=async()=>{loading(true);try{if(state.mode==='supabase')await fetchData();else{const d=localLoad();state.entries=d.entries||[];state.payments=d.payments||[]}renderAll();toast('تم التحديث ↻')}catch{toast('تعذر التحديث')}finally{loading(false)}};
  $('#authForm').addEventListener('submit',authSubmit);$('#toggleAuthMode').onclick=()=>{state.authMode=state.authMode==='login'?'signup':'login';updateAuthMode()};$('#demoBtn').onclick=async()=>{state.mode='local';state.user=null;await enterApp()};
  $('#logoutBtn').onclick=logout;$('#settingsLogoutBtn').onclick=logout;$('#exportBtn').onclick=exportBackup;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>importBackup(e.target.files[0]);
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('#installBtn').classList.add('hidden')};
  document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.open').forEach(m=>closeModal(m.id))});
}

init().catch(e=>{console.error(e);toast('حدث خطأ أثناء تشغيل التطبيق')});
