import { createClient } from 'npm:@supabase/supabase-js@2';
const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8'};
const enc=new TextEncoder();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
const unhex=(h:string)=>new Uint8Array(h.match(/.{1,2}/g)?.map(x=>parseInt(x,16))||[]);
const rnd=(n=32)=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return hex(b)};
const sha=async(s:string)=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))));
const validPin=(p:unknown)=>typeof p==='string'&&/^\d{4}$/.test(p);
const safeEq=(a:string,b:string)=>{if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0};
async function derive(pin:string,salt:string,iterations:number){const key=await crypto.subtle.importKey('raw',enc.encode(pin),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unhex(salt),iterations},key,256);return hex(new Uint8Array(bits))}
async function session(){const token=rnd(32),token_hash=await sha(token),expiresAt=new Date(Date.now()+30*86400000).toISOString();const {error}=await supabase.from('tahweeshti_sessions').insert({token_hash,expires_at:expiresAt});if(error)throw error;return{token,expiresAt}}
async function requireSession(req:Request){const a=req.headers.get('authorization')||'',t=a.startsWith('Bearer ')?a.slice(7).trim():'';if(!t)return null;const h=await sha(t),now=new Date().toISOString();const {data}=await supabase.from('tahweeshti_sessions').select('id').eq('token_hash',h).gt('expires_at',now).maybeSingle();if(!data)return null;await supabase.from('tahweeshti_sessions').update({last_seen_at:now}).eq('id',data.id);return data}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 let b:any={};try{b=await req.json()}catch{} const action=String(b.action||'');
 try{
  if(action==='status'){const {data}=await supabase.from('tahweeshti_settings').select('id').eq('id',1).maybeSingle();return json({initialized:!!data})}
  if(action==='setup'){if(!validPin(b.pin))return json({error:'الرمز لازم يكون 4 أرقام.'},400);const {data:x}=await supabase.from('tahweeshti_settings').select('id').eq('id',1).maybeSingle();if(x)return json({error:'تم إنشاء الحساب مسبقًا.'},409);const salt=rnd(16),iterations=120000,pin_hash=await derive(b.pin,salt,iterations);const {error}=await supabase.from('tahweeshti_settings').insert({id:1,pin_salt:salt,pin_hash,iterations});if(error)throw error;return json({ok:true,...await session()})}
  if(action==='login'){if(!validPin(b.pin))return json({error:'الرمز لازم يكون 4 أرقام.'},400);const {data:s}=await supabase.from('tahweeshti_settings').select('*').eq('id',1).maybeSingle();if(!s)return json({error:'الحساب غير مهيأ بعد.'},404);const h=await derive(b.pin,s.pin_salt,Number(s.iterations));if(!safeEq(h,s.pin_hash))return json({error:'رمز الدخول غير صحيح.'},401);return json({ok:true,...await session()})}
  const s=await requireSession(req);if(!s)return json({error:'انتهت الجلسة. سجّل الدخول من جديد.'},401);
  if(action==='session')return json({ok:true});
  if(action==='logout'){await supabase.from('tahweeshti_sessions').delete().eq('id',s.id);return json({ok:true})}
  if(action==='list'){const [e,p]=await Promise.all([supabase.from('tahweeshti_shared_entries').select('*').order('entry_date',{ascending:false}).order('created_at',{ascending:false}),supabase.from('tahweeshti_shared_payments').select('*').order('payment_date',{ascending:false}).order('created_at',{ascending:false})]);if(e.error)throw e.error;if(p.error)throw p.error;return json({entries:e.data||[],payments:p.data||[]})}
  if(action==='entry_upsert'){const e=b.entry||{};if(!['receivable','payable','income','expense'].includes(e.type)||!(Number(e.amount)>0))return json({error:'بيانات الحركة غير صالحة.'},400);const id=e.id||crypto.randomUUID();const row={id,type:e.type,person:String(e.person||'').slice(0,120),amount:Number(e.amount),entry_date:e.date,note:String(e.note||'').slice(0,800),receipt_path:e.receiptPath||null,updated_at:new Date().toISOString()};const {error}=await supabase.from('tahweeshti_shared_entries').upsert(row,{onConflict:'id'});if(error)throw error;return json({ok:true,id})}
  if(action==='entry_delete'){const id=String(b.id||'');const {data:e}=await supabase.from('tahweeshti_shared_entries').select('receipt_path').eq('id',id).maybeSingle();if(e?.receipt_path)await supabase.storage.from('receipts').remove([e.receipt_path]);const {error}=await supabase.from('tahweeshti_shared_entries').delete().eq('id',id);if(error)throw error;return json({ok:true})}
  if(action==='payment_add'){const p=b.payment||{};const {error}=await supabase.from('tahweeshti_shared_payments').insert({entry_id:p.entryId,amount:Number(p.amount),payment_date:p.date,note:String(p.note||'').slice(0,600)});if(error)return json({error:error.message.includes('exceeds')?'الدفعة أكبر من المتبقي.':'تعذر حفظ الدفعة.'},400);return json({ok:true})}
  if(action==='receipt_upload'){const mime=String(b.mime||''),base64=String(b.base64||'');if(!['image/jpeg','image/png','image/webp'].includes(mime))return json({error:'نوع الصورة غير مدعوم.'},400);const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));if(bytes.byteLength>5*1024*1024)return json({error:'حجم الصورة أكبر من 5MB.'},400);const ext=mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg',path=`shared/${b.entryId}/${Date.now()}-${rnd(6)}.${ext}`;const {error}=await supabase.storage.from('receipts').upload(path,bytes,{contentType:mime,upsert:true});if(error)throw error;return json({ok:true,path})}
  if(action==='receipt_url'){const {data,error}=await supabase.storage.from('receipts').createSignedUrl(String(b.path||''),120);if(error)throw error;return json({url:data.signedUrl})}
  if(action==='import'){const entries=Array.isArray(b.entries)?b.entries:[],payments=Array.isArray(b.payments)?b.payments:[];if(entries.length){const rows=entries.map((e:any)=>({id:e.id||crypto.randomUUID(),type:e.type,person:String(e.person||''),amount:Number(e.amount||0),entry_date:e.date,note:String(e.note||''),receipt_path:null,updated_at:new Date().toISOString()}));const {error}=await supabase.from('tahweeshti_shared_entries').upsert(rows,{onConflict:'id'});if(error)throw error}if(payments.length){const rows=payments.map((p:any)=>({id:p.id||crypto.randomUUID(),entry_id:p.entryId,amount:Number(p.amount||0),payment_date:p.date,note:String(p.note||'')}));const {error}=await supabase.from('tahweeshti_shared_payments').upsert(rows,{onConflict:'id'});if(error)throw error}return json({ok:true})}
  return json({error:'Unknown action'},400);
 }catch(err){console.error(err);return json({error:'حدث خطأ في الخادم.'},500)}
});
